### ISSUE TITLE
Semi-BUG: -D parameter doesn't work with SAT>IP

### ISSUE THREAD

**Issue by lars18th** [wirbel-at-vdr-portal/w_scan_cpp#11] opened 2023-09-27 18:25 UTC
Hi @wirbel-at-vdr-portal ,

I detected that with the `--satip-server` parameter the parameter `-D` to select the DiseqC LNB doesn't work. The tool every time requests the SETUP command with `?src=1` regardless of the `-D` value used.

**Comment by lars18th** [comment] 2023-09-28 07:45
Hi @wirbel-at-vdr-portal ,

I need your help to fix this issue:
- Inside the code, this line is the responsible of selecting the value of the `src=` parameter:
`int src = (strchr("S", type) && source) ? atoi(source->Description()) : 1;`
 https://github.com/wirbel-at-vdr-portal/vdr-plugin-satip/blob/974dffd946d3c7c208bd12996fb3f1e9691b4a97/param.c#L195
- Therefore, my assumption is that we need to add in the `Sources` structure one source with the `description` member set to the number of the source. That's `1` (as string) for SRC=1, `2` for SRC=2, etc. 
- To achieve this, as the `Sources` is empty _inside_ the "w_scan_cpp" tool (not inside the standard VDR), my idea is to create one entry in the list (in the initialization section of the w_scan_cpp) with the number set by the `-D` parameter. But I need to know the `Index` integer of the "channel" used for the scan, bacause the previous line `Sources.Get(channel->Source()` returns the element with this identifier. The problem here is that this identifier doesn't change over the execution, but it's different for every scanning. Therefore, what I need to do to get the correct value?

You know any idea to overcome this problem?
Thank you.

**Comment by wirbel-at-vdr-portal** [comment] 2023-09-28 08:35
Param -D is for **diseqc switches** connected to a local tuner, so it's not a bug. It's something completly _different_ than choosing the preconfigured RF input of an SAT>IP server.

It's just not implemented, as no-one needed it so far.

Probably a new option --satip-src is better idea. But that means to update docs together with that changes, man page and help texts.

But basically, this is the way to go.
- Probably in CmdOpts.cpp:411
- create a new cSource with default constructor
- call it's Parse with argument (Source + ' ' + IntToStr(src)).c_str()
- add this Sources

**Comment by wirbel-at-vdr-portal** [comment] 2023-09-28 15:25
Please check.



diff --git a/CmdOpts.cpp b/CmdOpts.cpp
index f828558..64e1df5 100644
--- a/CmdOpts.cpp
+++ b/CmdOpts.cpp
@@ -126,6 +126,7 @@ bool ParseArguments(int argc, char* argv[]) {
   std::string Source("S19.2E");
   int RotorPosition = 9999;
   bool use_satip = false;
+  int satip_src = 1;

   size_t p = ProgName.find_last_of("/\\");
   if (p != std::string::npos)
@@ -274,6 +275,10 @@ bool ParseArguments(int argc, char* argv[]) {
         WirbelscanSetup.SatipSvr = Param;
         i++;
         }
+     else if (Argument == "--satip-src") {
+        PARAM("1,2,3,4");
+        satip_src = StrToInt(Param);
+        }
      else if ((Argument == "-i") or (Argument == "--inversion")) {
         PARAM("0,1,2");
         if      (Param == "0") WirbelscanSetup.DVBC_Inversion = 0;
@@ -408,6 +413,11 @@ bool ParseArguments(int argc, char* argv[]) {
      case 1 /* C */: break;
      case 2 /* S */:
         {
+        if (use_satip and satip_src > 1) {
+           cSource* source = new cSource;
+           source->Parse((Source + ' ' + IntToStr(satip_src)).c_str());
+           Sources.Add(source);
+           }
         if (not DiseqcSwitch.empty())
            DiseqcSwitchConfig(Source, Setup.LnbFrequLo, Setup.LnbFrequHi, Setup.LnbSLOF, DiseqcSwitch);
         else if (not Scr.empty())

**Comment by wirbel-at-vdr-portal** [comment] 2023-09-28 15:34
please check
[diff.txt](https://github.com/wirbel-at-vdr-portal/w_scan_cpp/files/12751406/diff.txt)

**Comment by lars18th** [comment] 2023-09-28 16:15
Hi @wirbel-at-vdr-portal ,

> please check [diff.txt](https://github.com/wirbel-at-vdr-portal/w_scan_cpp/files/12751406/diff.txt)

We've do it at the same time... and more or less with the same approach. 😆 

In any case, please consider my version; and take note of these points:
- In the SAT>IP protocol you can use more than 4 sources. So it has sense to support up to 16.
- The "new" parameter satip-src seems to be redundant. The same can be obtained using "-D nn". Then no new code is necessary to parse it. Futhermore, this parameter in fact is indicating the same as SRC.
- I've added the necessary checks to overcome potential errors, then my code is robust.

But please merge/commit whatever you prefer. IMHO following the KISS model is preferable and the "-D" use is more clean. It doesn't break anything and it only extends functionality.

**Comment by wirbel-at-vdr-portal** [comment] 2023-10-01 09:18
Now in main as parameter --satip-src.

**Comment by wirbel-at-vdr-portal** [comment] 2023-10-06 15:28
I would like to close soon, if you don't have further issues here.

**Comment by wirbel-at-vdr-portal** [comment] 2023-10-08 12:34
I'm closing, as no more activity is here. Feel free to re-open, if it doesn't work.

**Closed as completed by wirbel-at-vdr-portal** 2023-10-08 12:34 UTC
